### ISSUE TITLE
Add Personas to /web-lit-whitepaper

### ISSUE THREAD

**Issue by sabrinang** [mozilla/content#1]
Since Web Literacy 2.0 personas are not going to be on the web literacy map page, there was interest for the text to live on the whitepaper. @anmechung Please confirm and advise where you prefer the persona text should be placed in the whitepaper on: http://mozilla.github.io/content/web-lit-whitepaper/

**Persona Text:**

**Teacher**
My name is Mr. G and I am a high school music teacher. I’m interested in teaching my students to be responsible citizens of the web given how active they are in making and remixing digital music. With all the issues about copyrights and licenses, I need resources that will help educate me and them about these issues as well how to be a good collaborator and leader.

**Afterschool Educator**
My name is Maya, and I work at an afterschool program where middle school students participate in a variety of activities from homework help to creating their own online movies. Kids love this program, but we have parents who are concerned about security and privacy. We need a workshop or set of activities to help participants and their parents understand how to protect their privacy and be able to develop and share movies in the open.

**Researcher**
My name is Jane and I am a professor at a research university. I’m want to learn how to effectively data mine and publish my research online. I need basic digital literacy skills to understand how best to search and aggregate data online, and how to post my research in the open for feedback and comment. I need a MOOC to learn these skills and a way to and collaborate with other colleagues to develop common practices.

**Activist**
My name is Roshni and am a self-proclaimed programmer who started coding on my own as a teen. I now own my own start-up technology company, and the more time I spend collaborating online, and understanding the most critical innovation of my generation, I’m realizing how vital it is for me to teach and educate others about how to protect the web as a vital public resource. I need resources to teach others about basic web literacy skills, and campaigns to invigorate them about why they should care about the web.

**Welder**
My name is Adeo and I am learning to be a welder in a job training program. I want to start my own business, and need to learn how to use the internet to build a website, find partners, and create jobs for others in my community. I need low-cost tools and an online community to learn these skills and promote his new business. 

cc/ @flukeout @hannahkane

**Comment by anmechung** [comment]
@sabrinang is it possible to have personas running along the right hand side of paper?  with head shot of a person? 
cc/@flukeout @hannahkane

**Comment by sabrinang** [comment]
@anmechung I believe it is possible however I would suggest an alternative to the personas being on the right side as it would distract from the main content and interfere with the full width of the main body copy as the template currently is. 

I think an option of arranging this persona content is for it to be near the References section of the paper since personas on their own on the right would feel out of place so it can be grouped with the other reference-y material. Also, I think it’ll be important to introduce the personas with context about how these are relevant and how they emerged to be the audience we had in mind while designing Web Literacy 2.0 etc. 

To introduce personas early on in the paper, I think we can link "diverse audiences" in the intro text here: 

> This paper captures the evolution of the Mozilla Web Literacy Map to reach and meet the growing number of **diverse audiences** using the web.

 to an anchor link (example: http://mozilla.github.io/content/web-lit-whitepaper/#personas) that points to this section on the paper below.

Yes, we can find some headshots/visuals to go along side these.

**Comment by anmechung** [comment]
@sabrinang good idea - let's do it the way you are suggesting.

**Comment by flukeout** [comment]
That sounds good to me. I can get started on the content updates and design on Monday. 

@sabrinang Do you know of any good resources for headshots or do you have some images in mind?

**Comment by kristinashu** [comment]
Here are a bunch of images I pulled off flickr search with either the Creative Commons license or Modifications Allowed license: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLLWhDYkxLOWZEbU0&usp=sharing

**Comment by sabrinang** [comment]
Great photos! I chose 5 photos to use and using circle container shape (exception for profile images https://github.com/mozilla/teach.mozilla.org/issues/1376). See mockup below:
![web-literacy-white-paper_personas-circle](https://cloud.githubusercontent.com/assets/2492510/14118200/2f0490d0-f59d-11e5-9aa5-95a36bf9f568.png)

@flukeout Can you walk me through how to add these images?

**Comment by sabrinang** [comment]
Exploring more photo options: 
![web-literacy-white-paper_personas-circle-2](https://cloud.githubusercontent.com/assets/2492510/14125679/58e3bbf0-f5c1-11e5-90f9-a20730588837.png)

**Comment by anmechung** [comment]
@sabrinang  Let's go with these.  Thanks!

**Comment by flukeout** [comment]
Done!
