### ISSUE TITLE
Need to add a section for funders

### ISSUE THREAD

**Issue by brettgaylor** [mozilla/content#16]
Hi folks - I realized I made a big ommission.  Ford are not the only funders of this program, and we could potentially find ourselves in a jam if we don't credit the right funders.

We need to also credit Google and the Media Democracy Fund.

I think we should just add a page that says "partners", and add the following text:

"Funding for the Open Web Fellows was provided by:

Ford logo

Google Logo 

Media Democracy Fund Logo

I'll reach out to folks to get the finer points of these cleared up.  Sorry for this large ommission!

Brett

**Comment by flukeout** [comment]
No problem @brettgaylor - should we take down the whitepaper until that content is up?

@kristinashu do you want to take a crack at the design of this page? I can implement when it's ready.

**Comment by brettgaylor** [comment]
Nope, no need to take it down.

**Comment by brettgaylor** [comment]
I discussed this with Kalpana - she didn't think there was a necessity to halt publication. We are going to reach out to these funders and add logos if they need to see them.  So - probably no need to take action on this right away :)

**Comment by kristinashu** [comment]
Ok cool, we'll hold off for now.

**Comment by flukeout** [comment]
Okay, closing until further notice.
