### ISSUE TITLE
Complete edits to Web LIt 2.0 paper

### ISSUE THREAD

**Issue by anmechung** [mozilla/content#3]
@flukeout - a few more edits to complete:
- Change title and sub-title to Web Literacy 2.0 at the top of the page, and in the middle of the paper. (i.e. eliminate Digital-Age Skills)
- Add hyphen in between Problem and Solving (subtitle under 21st Century Skills and Leadership Development section)
- Add a link to the original white paper after the conclusion section. 
- Linked to web lit map when its available.
  cc/@sabrinang @hannahkane

**Comment by flukeout** [comment]
@anmechung 

I've made the requested changes and linked the Google Docs version of the paper at the bottom of the Conclusion section. It looks like only people within the Mozilla organization on Google Docs are able to see it though - do you want to change the permission settings on it, or do you have another version of if that we can link to?

Please look over http://mozilla.github.io/content/web-lit-whitepaper/ and file new issues if necessary.
